import { BREED_PROFILES } from "../../config/breedProfiles.js";

/**
 * Service: Bird Heat Production Engine (Module 01)
 * 
 * Formulas:
 * 1. Heat Per Bird (Watts) = Lookup Value based on Breed and Bird Age
 * 2. Total House Heat Load (Watts) = Heat Per Bird (Watts) * Current Bird Count
 * 3. Total House Heat Load (kW) = Total House Heat Load (Watts) / 1000
 * 
 * Purpose:
 * Calculates metabolic heat emissions generated by the flock. Heat load is crucial 
 * for sizing minimal ventilation (to prevent heat accumulation) and calculating 
 * cooling pad activation schedules.
 * 
 * Inputs:
 * - age (Number): Bird age in days.
 * - birdCount (Number): Total birds inside the shed.
 * - breed (String): Selected bird breed ("Cobb 500", "Ross 308", "Arbor Acres", "Indian River").
 * 
 * Outputs:
 * - heatProductionDetails (Object): Weight, heat per bird, and total heat load metrics.
 * 
 * Units:
 * - Weight: Kilograms (kg)
 * - Heat: Watts (W) and Kilowatts (kW)
 * 
 * Engineering Assumptions:
 * - Relies on static age-to-weight and weight-to-heat lookup tables calibrated for standard 
 *   ambient zones. Breed profiles prevent setpoint mismatch.
 */

export const calculateBirdHeat = (age, birdCount, breed) => {
  const ageVal = parseInt(age) || 1;
  const countVal = parseInt(birdCount) || 0;
  const selectedBreed = breed || "Cobb 500";

  // Match breed configurations
  const breedData = BREED_PROFILES[selectedBreed] || BREED_PROFILES["Cobb 500"];
  
  // Find record for current age
  const record = breedData.find(r => ageVal <= r.maxAge) || breedData[breedData.length - 1];

  const birdWeight = record.weightKg;
  const heatPerBird = record.heatWatts;
  const totalHeatWatts = heatPerBird * countVal;
  const totalHeatKw = parseFloat((totalHeatWatts / 1000).toFixed(2));

  return {
    birdAge: ageVal,
    birdWeight,
    heatPerBird,
    totalHeatWatts,
    totalHeatKw
  };
};
